-- Script para criar a estrutura de controle de visitas no Supabase (PostgreSQL)
-- Ajuste os nomes dos esquemas ou roles caso necessario antes de executar.

-- 1. Garante que as funcoes para UUID estejam disponiveis
create extension if not exists "uuid-ossp";

-- 2. Tabela principal de visitantes
create table if not exists public.entrou (
    id uuid primary key default uuid_generate_v4(),
    numero text not null unique,
    visit_count integer not null default 0,
    first_visit timestamptz not null default timezone('utc', now()),
    last_visit timestamptz not null default timezone('utc', now()),
    metadata jsonb default '{}'::jsonb
);

comment on table public.entrou is 'Visitantes identificados pelo numero informado e estatisticas de acesso.';
comment on column public.entrou.numero is 'Identificador fornecido pelo visitante (ex.: numero de telefone).';
comment on column public.entrou.visit_count is 'Total de vezes que o visitante acessou o site.';
comment on column public.entrou.first_visit is 'Data/hora (UTC) do primeiro acesso registrado.';
comment on column public.entrou.last_visit is 'Data/hora (UTC) do ultimo acesso registrado.';
comment on column public.entrou.metadata is 'Campo opcional para armazenar dados complementares em JSON.';

-- 3. Historico detalhado das visitas (opcional)
create table if not exists public.entrou_logs (
    id bigint generated by default as identity primary key,
    visitor_id uuid not null references public.entrou(id) on delete cascade,
    visited_at timestamptz not null default timezone('utc', now()),
    context jsonb default '{}'::jsonb
);

comment on table public.entrou_logs is 'Historico individual de cada visita registrada.';
comment on column public.entrou_logs.context is 'Informacoes extras (origem, user agent, etc.).';

-- 4. View auxiliar para resumir as visitas
create or replace view public.entrou_resumo as
select
    e.id,
    e.numero,
    e.visit_count,
    e.first_visit,
    e.last_visit,
    coalesce(jsonb_agg(el.visited_at order by el.visited_at desc)
             filter (where el.id is not null), '[]'::jsonb) as visitas
from public.entrou e
left join public.entrou_logs el on el.visitor_id = e.id
group by e.id;

-- 5. Politicas de Row Level Security (RLS)
-- Ative caso queira expor a tabela para o cliente anonimo com seguranca.
alter table public.entrou enable row level security;
alter table public.entrou_logs enable row level security;

create policy "Allow service role full access" on public.entrou
    for all using (auth.role() = 'service_role');

create policy "Allow service role full access" on public.entrou_logs
    for all using (auth.role() = 'service_role');

-- Ajuste ou adicione politicas extras conforme necessario para clientes anonimos ou usuarios autenticados.
